apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "teacher-web.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "teacher-web.name" . }}
    helm.sh/chart: {{ include "teacher-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "teacher-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "teacher-web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: {{ include "teacher-web.fullname" . }}-pvc
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: SERVER_NAME
            value: {{ include "teacher-web.name" . }}
          envFrom:
          - configMapRef:
              name: {{ include "teacher-web.fullname" . }}-conf
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          volumeMounts:
          - mountPath: /xdfapp/apps/tomcat/webapps/ROOT/WEB-INF/pages/vm
            name: vol1
            subPath: vm
          - mountPath: /xdfapp/apps/tomcat/webapps/ROOT/resources
            name: vol1
            subPath: resources
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
