apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-praxis
  labels:
    app.kubernetes.io/name: {{ include "teacher-web.name" . }}
    helm.sh/chart: {{ include "teacher-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-praxis
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "teacher-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}-praxis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "teacher-web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-praxis
    spec:
      containers:
        - name: praxis-svr
          {{- if .Values.env }}
          env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
          {{- end }}
          image: "{{ .Values.image.praxis.repository }}:{{ .Values.image.praxis.tag }}"
          imagePullPolicy: {{ .Values.image.praxis.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
