apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "teacher-web.fullname" . }}-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /xdfapp/data/nfs/fpl-java-web
    server: 10.10.0.208
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs