apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teacher-web.fullname" . }}-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ include "teacher-web.fullname" . }}-pv
  storageClassName: nfs